<?php
$_['text_title_genoapay'] = 'Genoapay';
$_['button_confirm'] = 'Place order';
$_['payment_success_message'] = 'Payment was successful via %3$s. Amount: %1$s. Payment ID: %2$s';
$_['order_cancelled_message'] = 'Your purchase has been cancelled.';

//HTML for product info page
$_['text_info_payment_with_amount'] = '<div style=" margin-bottom: 10px;"><a style="text-decoration: none;" href="javascript: void(0)" id="genoapay-popup"> <img src="image/catalog/genoapay.svg" style="padding-right: 5px; max-width: 110px;"> <span style="font-size: 15px;padding-right: 5px;color: rgb(46, 46, 46);"> 10 weekly payments of <strong>{{{amount}}}</strong> </span> <span style="color: rgb(49, 181, 156); font-weight: bold; font-size:13px;">learn more</span> </a></div>';
$_['text_info_payment'] = '<div style="margin-bottom: 10px;" class="wc-latitudefinance-genoapay-container"><a style="text-decoration: none;" href="javascript: void(0)" id="genoapay-popup"> <img src="image/catalog/genoapay.svg" style="padding-right: 5px; max-width: 110px;"> <span style="font-size: 15px;padding-right: 5px;color: rgb(46, 46, 46);"> Available now. </span> <span style="color: rgb(49, 181, 156); font-weight: bold; font-size:13px;">learn more</span> </a></div>';

//HTML for checkout page
$_['text_info_payment_checkout'] = "<div class='wc-latitudefinance-payment-method-container'> <div style='margin:10px 0;'> <img src='image/catalog/genoapay.svg' alt='Genoapay Payment' title='Genoapay Payment'/> <p style='font-weight: 700; line-height: 24px;'>Shop now pay later. <a style='text-decoration: none;' href='javascript: void(0)' id='genoapay-popup'> <span style='text-decoration: none;font-weight: bold; font-size:13px; margin-left: 5px; color: rgb(49, 181, 156)'>Learn more</span> </a> </p><p>10 weekly payments of <strong style='color:rgb(49, 181, 156)'>%s</strong></p></div><p style='font-size: 22px; color:rgb(49, 181, 156); font-weight: 600; margin-bottom: 20px'>No interest.<span style='text-decoration: underline; margin-left: 5px;'>Ever.</span></p></div>";

//Modal
$_['text_genoapay_modal'] = '<div class="g-infomodal-container" id="g-infomodal-container" style="display: none;"> <div class="g-infomodal-content"> <img id="g-infomodal-close" class="g-infomodal-close" src="image/catalog/close_btn_gen_green.svg"> <div class="g-infomodal-inner"> <div class="g-modal-header"> <img class="g-infomodal-logo" src="image/catalog/genoapay_logo_white.svg"> <span>Pay over 10 weeks.<br>No interest, no fees.</span> </div><div class="g-infomodal-body"> <div class="g-infomodal-card-group"> <div class="g-infomodal-card"> <div class="g-infomodal-card-content"> <img src="image/catalog/shopping_trolly_icon.svg"> </div><div class="g-infomodal-card-footer"> <div class="g-infomodal-card-title"><span>Checkout with </span><span>Genoapay</span></div></div></div><div class="g-infomodal-card"> <div class="g-infomodal-card-content"> <img src="image/catalog/thin_tick_icon.svg"> </div><div class="g-infomodal-card-footer"> <div class="g-infomodal-card-title"><span>Credit approval </span><span>in seconds</span></div></div></div><div class="g-infomodal-card"> <div class="g-infomodal-card-content"> <img src="image/catalog/get_it_now_icon.svg"> </div><div class="g-infomodal-card-footer"> <div class="g-infomodal-card-title"><span>Get it now, </span><span>pay over 10 weeks</span></div></div></div></div><p>That\'s it! We manage automatic weekly payments until you\'re paid off. Full purchase details can be viewed anytime online.</p><hr> <p>You will need</p><ul class="g-infomodal-list"> <li>To be over 18 years old</li><li>Visa/Mastercard payment</li><li>NZ drivers licence or passport</li><li>First instalment paid today</li></ul> <div class="g-infomodal-terms">Learn more about <a href="https://www.genoapay.com/how-it-works/" target="_blank">how it works</a>. Credit criteria applies. Weekly payments will be automatically deducted. Failed instalments incur a $10 charge.See our <a href="https://www.genoapay.com/terms-and-conditions/" target="_blank">Terms &amp; Conditions</a> for more information.</div></div></div></div></div>';
