<?php
$_['text_title_latitude_pay'] = 'LatitudePay';
$_['button_confirm'] = 'Place order';
$_['payment_success_message'] = 'Payment was successful via %3$s. Amount: %1$s. Payment ID: %2$s';
$_['order_cancelled_message'] = 'Your purchase has been cancelled.';

//HTML for product info page
$_['text_info_payment_with_amount'] = "<div style='margin-bottom: 10px;' class='wc-latitudefinance-latitudepay-container'> <a style='text-decoration: none;' href='javascript: void(0)' id='latitudepay-popup'> <img src='image/catalog/latitude_pay.svg' style='padding-right: 5px; max-width: 110px;'> <span style='font-size: 15px;padding-right: 5px;color: rgb(46, 46, 46);'> 10 weekly payments of <strong>{{{amount}}}</strong> </span> <span style='color: rgb(57, 112, 255); font-weight: bold; font-size:13px;'>learn more</span> </a>";
$_['text_info_payment'] = "<div style='margin-bottom: 10px;' class='wc-latitudefinance-latitudepay-container'> <a style='text-decoration: none;' href='javascript: void(0)' id='latitudepay-popup'> <img src='image/catalog/latitude_pay.svg' style='padding-right: 5px; max-width: 110px;'> <span style='font-size: 15px;padding-right: 5px;color: rgb(46, 46, 46);'> Available now. </span> <span style='color: rgb(57, 112, 255); font-weight: bold; font-size:13px;'>learn more</span> </a>";

//HTML for checkout page
$_['text_info_payment_checkout'] = "<div class='wc-latitudefinance-payment-method-container'> <div style='margin:10px 0;'> <img src='image/catalog/latitude_pay.svg' alt='Latitude Payment' title='Latitude Payment'/> <p style='font-weight: 700; line-height: 24px;'>Shop now pay later. <a style='text-decoration: none;' href='javascript: void(0)' id='latitudepay-popup'> <span style='text-decoration: none;font-weight: bold; font-size:13px; margin-left: 5px; color: rgb(57, 112, 255)'>Learn more</span> </a> </p><p>10 weekly payments of <strong style='color:rgb(57, 112, 255)'>%s</strong></p></div><p style='font-size: 22px; color:rgb(57, 112, 255); font-weight: 600; margin-bottom: 20px'>No interest.<span style='text-decoration: underline; margin-left: 5px;'>Ever.</span></p></div>";

//Modal
$_['text_latitude_pay_modal'] = "<link rel='stylesheet' href='catalog/view/javascript/latitude_pay/css/style.css' />" .
    "<div class='lp-modal-container' id='lp-modal-container' style='display: none;'> <div class='lp-modal'> <div class='lp-content'> <div class='modal-header lp-header'> <button id='lp-modal-close' aria-hidden='true' class='lp-close-container' type='button'>×</button> <h4 class='modal-title text-center'> <img class='lp-logo' src='image/catalog/lpay_modal_logo.png'> </h4> </div><div class='modal-body p-0'> <div class='lp-content'> <div class='lp-body'> <div class='lp-heading lp-block'> <div> How does this work? </div><div class='lp-bold'> Glad you asked! </div></div><ul class='lp-steps lp-block'> <li> <img src='image/catalog/lp_phone.png' style='margin-left: auto;margin-right: auto;'> <div class='lp-subheading'> Choose LatitudePay <br class='lp-line-break'> at the checkout') ?> </div><span> There is no extra cost to you - just select it as your <br class='lp-line-break'> payment option. </span> </li><li> <img src='image/catalog/lp_timer.png' style='margin-left: auto;margin-right: auto;'> <div class='lp-subheading'> Approval in <br class='lp-line-break'> minutes </div><span> Set up your account and we will tell you straight away <br class='lp-line-break'> if approved. </span> </li><li> <img src='image/catalog/lp_calender.png' style='margin-left: auto;margin-right: auto;'> <div class='lp-subheading'> Get it now, pay <br class='lp-line-break'> over 10 weeks </div><span>It is the today way to pay, just 10 easy payments. <br class='lp-line-break'> No interest. Ever. </span> </li></ul> </div><div class='lp-requirements lp-block'> <div class='lp-subheading'> If you are new to LatitudePay, you will need this stuff: </div><ul class='lp-requirements-list'> <li>Be over 18 years old</li><li>An Australian driver’s licence or passport</li><li>A couple of minutes to sign up, <br class='lp-line-break'>it’s quick and easy </li><li>A credit/debit card (Visa or Mastercard)</li></ul> </div><div class='lp-footer lp-block'> Subject to approval. Conditions and late fees apply. Payment Plan provided by LatitudePay Australia Pty Ltd ABN 23 633 528 873. For complete terms visit<a href='https://latitudepay.com/terms' target='_blank'> latitudepay.com/terms</a> </div></div></div></div></div></div>".
"<script src='catalog/view/javascript/latitude_pay/js/l_modal.js' type='text/javascript'></script>";
